# version: '3.8'

services:
  app:
    build: .
    ports:
      - "8888:80"
      # - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=rental_management
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    # command: --default-authentication-plugin=mysql_native_password --ssl=0
    env_file:
      - backend/.env.production

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: 